### ISSUE TITLE
Linux version does not work

### ISSUE THREAD

**Issue by accuwau** [SvenGDK/PS-Classics-fPKG-Builder#2]
```zsh
❯ ./makePSClassicsfPKG
/home/anna/Desktop/main/apps/tools/PS Classics fPKG Builder v1
20240105
2024
22:38:12
Traceback (most recent call last):
  File "crc.py", line 19, in <module>
  File "crc.py", line 9, in getCRC1
FileNotFoundError: [Errno 2] No such file or directory: ''
[79623] Failed to execute script 'crc' due to unhandled exception!
```
that error happens after selecting my PS2 iso file...
I'm on Arch Linux KDE Wayland.

**Comment by SvenGDK** [comment]
> ```shell
> ❯ ./makePSClassicsfPKG
> /home/anna/Desktop/main/apps/tools/PS Classics fPKG Builder v1
> 20240105
> 2024
> 22:38:12
> Traceback (most recent call last):
>   File "crc.py", line 19, in <module>
>   File "crc.py", line 9, in getCRC1
> FileNotFoundError: [Errno 2] No such file or directory: ''
> [79623] Failed to execute script 'crc' due to unhandled exception!
> ```
> 
> that error happens after selecting my PS2 iso file... I'm on Arch Linux KDE Wayland.

Hi, what game are you using ? Asian (JP, Chinese, Korean, ...) games are not working at the moment.

**Comment by accuwau** [comment]
im just using a usa copy of silent hill 2, could my game dump be bad?

EDIT: seems running the windows version under wine worked. so it seems the linux version is just not working as intended

**Comment by SvenGDK** [comment]
> im just using a usa copy of silent hill 2, could my game dump be bad?
> 
> EDIT: seems running the windows version under wine worked. so it seems the linux version is just not working as intended

The US image should work fine. It seems like Arch Linux treats the files differently and the tool needs to be adapted.
I will set up Arch Linux in a VM and do some tests.

**Comment by A1asd** [comment]
I have the same problem on openSuse Tumbleweed. I will try the windows version

edit: Just tried the windows version with wine but had no luck. It crashes for me when selecting the PS2 or PSP tab
